<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
<!--		<title><?php echo htmlspecialchars($vocab->label()); ?></title> -->
        <title>ODRL Vocabulary &amp; Expression</title>
		<meta content="text/html; charset=utf-8" http-equiv="content-type" />
		<meta content="width=device-width,initial-scale=1" name="viewport" />
		<script class="remove" src="https://www.w3.org/Tools/respec/respec-w3c-common"></script>
		<script class="remove" src="config.js"></script>
		<style>
.nanotabs > ul li { float:left; list-style:none; }
.nanotabs > ul li a { display:block; padding:4px 6px; margin-right: 3px; border-left: 1px solid #b9ab2d; border-right: 1px solid #b9ab2d; border-top: 1px solid #b9ab2d; border-collapse: collapse; background:#fcfaee; color:#b9ab2d; font-family: sans-serif;
 text-decoration:none; }
.nanotabs > ul li a:hover { background:#FFFCE5; color:#550; }
.nanotabs > ul li a.selected { background:#555; color:#FFF; }
		</style>
	</head>
	<body>
<?php

//	echo $vocab->htmlHeader();
	
	readfile(dirname(__FILE__) . '/parts/abstract.html');
	readfile(dirname(__FILE__) . '/parts/sotd.html');
	readfile(dirname(__FILE__) . '/parts/intro.html');
?>
<section id="vocab">
	<h2>Vocabulary</h2>

	<p>The Namespace URI to identify the ODRL model and vocabulary terms is: <code>http://www.w3.org/ns/odrl/2/</code></p>

    <div class="issue" data-number="10">
        <p>The namespace URI may change in future versions.</p>
    </div>
    
<figure>
	<img src="diagram.png" alt="ODRL Vocabulary groups"/>
    <figcaption>Vocabulary groups </figcaption>
</figure>

     <div class="note">
        <p>Above figure will be updated to match the vocabulary term groupings.</p>
    </div>

    <p>The detail for each ODRL Vocabulary term is shown below in the two tables. The left table shows the normative semantic description of the concept, and the right table the ontological description and relationships.</p>
    
<?php
	echo $vocab->htmlTerms('Phpspecgen_Class', 'Classes');
	echo $vocab->htmlTerms('Phpspecgen_Property', 'Properties');
	echo $vocab->htmlTerms('Phpspecgen_ConceptScheme', 'Concept schemes');
	echo $vocab->htmlTerms('Phpspecgen_Concept', 'Concepts');
	echo $vocab->htmlTerms('Phpspecgen_Individual', 'Named individuals');
    echo $vocab->htmlSummaryOfTerms();
?>
    
    
</section>

        <section id="encodings">
	<h2>Vocabulary Encodings</h2>

    <section id="rdfowl">
   	<h2>RDF/OWL Encoding</h2>         
     <?php
        readfile(dirname(__FILE__) . '/parts/rdfowl.html');
        ?>
    </section>
          
    <section id="xml">
   	<h2>XML Encoding</h2>         
        <?php
        readfile(dirname(__FILE__) . '/parts/xml.html');  
          ?>
    </section>
            
    <section id="json">
   	<h2>JSON Encoding</h2>         
       <?php
        readfile(dirname(__FILE__) . '/parts/json.html');  
          ?>
    </section>
            
</section>
        
<section id="examples" class="informative">
	<h2>Scenarios - Encoding Examples</h2>
<?php
	$examples = array(
		'example1' => 'Set',
		'example2' => 'Offer',
		'example3' => 'Agreement',
		'example4' => 'Request',
		'example5' => 'Ticket',
		'example6' => 'Offer and next policy',
		'example7' => 'Privacy policy',
		'example8' => 'Permission and prohibition',
		'example9' => 'Inheritance',
		'example10' => 'Social network',
		'example11' => 'Multiple assets',
	);

	/* printExample(FILENAME-BASE, HTML-ID, TITLE); */

	foreach($examples as $name => $title)
	{
		printExample($name, 'sc-' . $name, $title);
	}
?>
</section>

             
   <section id="privacy">
   	<h2>Privacy Considerations</h2>         
     <?php
        readfile(dirname(__FILE__) . '/parts/privacy.html');
        ?>
    </section>
        
        
<section class="appendix normative" id="xmlschema">
<h2>ODRL XML Schema</h2>
      <?php
        $schema = file_get_contents("ODRL22.xsd");
        echo '<pre>' . htmlspecialchars($schema, ENT_QUOTES, 'UTF-8');
        echo '</pre>';
        ?>
</section>
        
<section class="appendix normative" id="jsonschema">
<h2>ODRL JSON Schema</h2>
       <?php
        $schema = file_get_contents("ODRL22.json");
        echo '<pre>' . htmlspecialchars($schema, ENT_QUOTES, 'UTF-8');
        echo '</pre>';
        ?>
 </section>
    
<section class="appendix" id="community">
<h2>Changes from the Community Group Reports</h2>
<p>
   None. 
</p> 
</section>
        
        
<script type="text/javascript" src="http://www.w3.org/scripts/nanotabs/0.9/nanotabs.js">
		</script>
		<script type="text/javascript">
nanotabs({c:"cell",e:"click",d:-1,f:function(){ return false; }});
nanotabs({c:"cell",e:"mouseover",s:"active"});
		</script>
	</body>
</html>

<?php

function printExample($filename, $id, $title)
{
	static $serialisations = array(
		'json' => 'JSON',
		'ttl' => 'Turtle',
		'xml' => 'XML',
		'rdf' => 'RDF/XML',
		'nt' => 'N-Triples',
	);
	
	echo '<section id="' . $id . '">';
	echo '<h3>' . $title . '</h3>';
	
	$basepath = dirname(__FILE__) . '/examples/' . $filename;
	
	@readfile($basepath . '.html');
	
	$versions = array();
	foreach($serialisations as $ext => $name)
	{
		if(file_exists($basepath . '.' . $ext))
		{
			$versions[$ext] = file_get_contents($basepath . '.' . $ext);
		}
	}
	
	echo '<div class="nanotabs">';
	echo '<ul>';
	foreach($versions as $ext => $payload)
	{
			echo '<li><a href="#' . $id . '-' . $ext . '" class="selected">' . $serialisations[$ext] . '</a></li>';
	}
	echo '</ul>';
	echo '</div>';

	$first = true;
	foreach($versions as $ext => $payload)
	{
		echo '<div id="' . $id . '-' . $ext . '" style="display: ' . ($first ? 'block' : 'none') . ';">';
		$first = false;
		echo '<pre class="example highlight ' . $ext . '">' . htmlspecialchars($payload, ENT_QUOTES, 'UTF-8') . '</pre>';
		echo '</div>';
	}
	
	echo '</section>';
}
